INSERT INTO USER_INFO (USER_ID, USER_DOB, USER_NAME) VALUES (1001, SYSDATE, 'Nilachal Chakraborty');
INSERT INTO USER_INFO (USER_ID, USER_DOB, USER_NAME) VALUES (2002, SYSDATE, 'Olivia Mallick');
INSERT INTO USER_INFO (USER_ID, USER_DOB, USER_NAME) VALUES (3003, SYSDATE, 'Diptendu Kundu');
INSERT INTO USER_INFO (USER_ID, USER_DOB, USER_NAME) VALUES (4004, SYSDATE, 'Rahul Dutta');